In [3]:
!pip install padelpy
import pandas as pd
import numpy as np
import seaborn as sns
import glob
from padelpy import padeldescriptor

! unzip fingerprints_xml.zip

xml_files = glob.glob("*.xml")
xml_files.sort()


bioactivity_DF = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DTI/data/normalized_data.csv')
bioactivity_DF.head(5)

Requirement already satisfied: padelpy in /usr/local/lib/python3.11/dist-packages (0.1.16)
unzip:  cannot find or open fingerprints_xml.zip, fingerprints_xml.zip.zip or fingerprints_xml.zip.ZIP.

,molecule_chembl_id,canonical_smiles,activity_class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,CHEMBL372889,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C(N)=O)ccc21,active,299.286,1.11984,1.0,5.0,7.602060
1,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,inactive,421.190,2.66050,0.0,4.0,4.869666
2,CHEMBL188484,O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc(I)cc21,active,403.175,3.76690,0.0,3.0,7.886057
3,CHEMBL362781,COc1ccc2c(c1)C(=O)C(=O)N2Cc1cc2ccccc2o1,active,307.305,3.17090,0.0,4.0,7.886057
4,CHEMBL191322,O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc([N+](=O)[O-])cc21,active,322.276,3.07050,0.0,5.0,7.619789

In [ ]:
filtered_DF = bioactivity_DF[['canonical_smiles', 'molecule_chembl_id']]
filtered_DF.head(10)

                                    canonical_smiles molecule_chembl_id
0          Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C(N)=O)ccc21       CHEMBL372889
1            O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21       CHEMBL185698
2             O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc(I)cc21       CHEMBL188484
3            COc1ccc2c(c1)C(=O)C(=O)N2Cc1cc2ccccc2o1       CHEMBL362781
4  O=C1C(=O)N(Cc2cc3ccccc3o2)c2ccc([N+](=O)[O-])cc21       CHEMBL191322
5                O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21       CHEMBL426082
6               Nc1cccc2c1N(Cc1cc3ccccc3s1)C(=O)C2=O       CHEMBL363243
7            O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21       CHEMBL365134
8  Cc1cc2c(c([N+](=O)[O-])c1)N(Cc1cc3ccccc3s1)C(=...       CHEMBL365677
9            COc1ccc2c(c1)C(=O)C(=O)N2Cc1cc2ccccc2s1       CHEMBL188811

In [ ]:
# Export data to csv format for padel readability.
filtered_DF.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [ ]:
## Molecular fingerprints are sorted and so are their respective xml files
fingerprints = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

FP_hashmap = dict(zip(fingerprints, xml_files))

In [ ]:
## Select for fingerprint (Substructure)
fingerprint = 'Substructure'
## Concat to output file name
fingerprint_output_file = ''.join([fingerprint,'.csv']) #Substructure.csv

# Retrieve fingerptint form hashtable
fingerprint_descriptortypes = FP_hashmap[fingerprint]

## Input smiles for molecules to test for activity
padeldescriptor(mol_dir = 'molecule.smi',
                d_file = fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml',
                descriptortypes = fingerprint_descriptortypes,
                detectaromaticity = True,
                standardizenitro = True,
                standardizetautomers = True,
                threads = 2,
                removesalt = True,
                log = True,
                fingerprints = True)

In [ ]:


features_DF = pd.read_csv(fingerprint_output_file)
features_DF.head(5)

,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,CHEMBL372889,1,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,CHEMBL185698,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,CHEMBL188484,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,CHEMBL362781,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,CHEMBL191322,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,1

In [ ]:

# Transform dataset to export
features_DF = features_DF.drop(columns=['Name'])
features_DF.head(5)

,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,SubFP10,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,1,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,0,0,1

In [ ]:

## Set the targets for pIC50 for regression model training.
targets = bioactivity_DF['pIC50']
model_input_DF = pd.concat([features_DF, targets], axis = 1)
model_input_DF.head(10)

,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,SubFP10,...,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307,pIC50
0,1,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.602060
1,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,4.869666
2,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.886057
3,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.886057
4,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,1,7.619789
5,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,4.882397
6,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.508638
7,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,6.008774
8,1,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,1,7.408935
9,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.568636

In [ ]:

# Export data for regression Model
model_input_DF.to_csv('regression_model_data.csv', index = False)

In [ ]:

# Remove pIC50 values and add activity levels instead for classification data
model_input_DF.drop(columns = ['pIC50'])
model_input_DF.head(5)

,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,SubFP10,...,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307,pIC50
0,1,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.602060
1,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,4.869666
2,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.886057
3,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,7.886057
4,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,1,7.619789

In [ ]:
## Extract class targets
targets = bioactivity_DF['activity_class']
## concatinate to DataFrame
model_input_DF = pd.concat([features_DF, targets], axis = 1)
model_input_DF.head(5)

,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,SubFP10,...,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307,activity_class
0,1,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,active
1,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,inactive
2,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,active
3,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,1,active
4,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,1,active

In [ ]:

## Export classfication model data
model_input_DF.to_csv('classification_model_data.csv', index = False)